# CCA175 Practice Exam
* Exam    : CCA175
* Title   : CCA Spark and Hadoop Developer Exam
* Vendor  : Cloudera
* Version : V12.35

IT Certification Guaranteed, The Easy Way!

Answer

## NO.13 CORRECT TEXT
### Problem Scenario 73 : 

You have been given data in json format as below.

{"first_name":"Ankit", "last_name":"Jain"}
{"first_name":"Amir", "last_name":"Khan"}
{"first_name":"Rajesh", "last_name":"Khanna"}
{"first_name":"Priynka", "last_name":"Chopra"}
{"first_name":"Kareena", "last_name":"Kapoor"}
{"first_name":"Lokesh", "last_name":"Yadav"}

Do the following activity

1. create employee.json file locally.
2. Load this file on hdfs
3. Register this data as a temp table in Spark using Python.
4. Write select query and print this data.
5. Now save back this selected data in json format.

#### Answer

In [5]:
hdfs dfs -put employee.json employee.json

in pyspark

In [7]:
# create a sqlContext
sqlContext = SQLContext( sc )

# load json file
df = sqlContext.jsonFile( 'employee.json' )

# register table
df.registerTempTable( 'employee' )

# make query
result = sparkContext.sql( 'SELECT * FROM employees' )
result.show()

# save back to hdfs
result.write.format( 'json' ).save( 'employee_result' )

end
---